name: const_date_time
description: A drop-in replacement for Dart's DateTime class with const constructors.
version: 1.0.0
repository: https://github.com/westy92/const-date-time
documentation: https://westy92.github.io/const-date-time/
issue_tracker: https://github.com/westy92/const-date-time/issues
funding: https://github.com/sponsors/westy92

environment:
  sdk: '>=2.18.0 <3.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
